# .github/workflows/python-test.yml

name: Chatbot CI/CD Pipeline

on:
  push:
    - main
    - testing
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Setting up devops"