# .github/workflows/python-test.yml

name: Chatbot CI/CD Pipeline

on:
  push:
    branches:
      - main
      - testing
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r docs/backend_requirements.txt
        pip install google-genai google-api-core python-dotenv
        pip install pytest
    
    - name: Establish Secrets
      env:
        GOOGLE_API_KEY = ${{Secrets.GOOGLE_API_KEY}}
        GROQ_API_KEY = ${{Secrets.GROQ_API_KEY}}
        

    - name: Test Pytests
      run: |
        python -m pytest tests/