# .github/workflows/python-test.yml

name: Chatbot CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    - main

jobs:
  runs-on: ubuntu-latest
  steps:
    - run: echo "Setting up devops"